---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin2
  namespace: flux-system
spec:
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-flux-config
  interval: 10m0s
  path: ./apps/admin2/${ENVIRONMENT}/${CLUSTER}
  postBuild:
    substitute:
      NAMESPACE: "admin2"
      WI_NAME: "admin2"