apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin
  namespace: flux-system
spec:
  path: ./apps/admin/${ENVIRONMENT}/base
  postBuild:
    substitute:
      NAMESPACE: "admin"
      WI_NAME: admin
