---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin
  namespace: flux-system
spec:
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-team
  interval: 10m0s
  path: ./apps/admin/staging/00
  postBuild:
    substitute:
      NAMESPACE: "admin"
      WI_NAME: "admin"