---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/admin/${ENVIRONMENT}/${CLUSTER}
  postBuild:
    substitute:
      NAMESPACE: "admin"
      WI_NAME: "admin"