apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-kubernetes
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/hello-kubernetes/${ENVIRONMENT}/base
  sourceRef:
    kind: GitRepository
    name: dev-team
    namespace: flux-system
  prune: true
  postBuild:
    substitute:
      NAMESPACE: "hello-kubernetes"
      WI_NAME: hello-kubernetes