apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/base/kustomize.yaml
patches:
  - path: ../../../apps/base/kustomize.yaml
    target:
      kind: Kustomization
      annotationSelector: hmcts.github.com/kustomize-defaults != disabled
  - path: ../../../apps/hello-kubernetes/staging/base/kustomize.yaml