apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin
  namespace: flux-system
spec:
  postBuild:
    substitute:
      ENVIRONMENT: "staging"
      WI_ENVIRONMENT: "staging"
      CLUSTER: "00"