apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../../hello-kubernetes
- ../../base/

patches:
  - path: ../../../base/kustomize.yaml
    target:
      kind: Kustomization
      annotationSelector: hmcts.github.com/kustomize-defaults != disabled